"""add name to doctor

Revision ID: 078c1c11c4d1
Revises: 16f3e1d08421
Create Date: 2025-12-26 23:02:44.162608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '078c1c11c4d1'
down_revision: Union[str, None] = '16f3e1d08421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='Unknown'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'name')
    # ### end Alembic commands ###
