"""add_slug_to_tenant

Revision ID: 08f9ce7caa02
Revises: f0cda9c0c460
Create Date: 2025-12-25 16:35:05.826056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08f9ce7caa02'
down_revision: Union[str, None] = 'f0cda9c0c460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_column('tenants', 'slug')
    # ### end Alembic commands ###
