"""Add AppUser table

Revision ID: 16f3e1d08421
Revises: 08f9ce7caa02
Create Date: 2025-12-26 14:05:22.698498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16f3e1d08421'
down_revision: Union[str, None] = '08f9ce7caa02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('otp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('otp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_phone'), 'app_users', ['phone'], unique=True)
    op.add_column('doctors', sa.Column('is_consulting', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'is_consulting')
    op.drop_index(op.f('ix_app_users_phone'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
