"""refactor_user_doctor_models

Revision ID: 28c33500c6c7
Revises: 293fd6785dfc
Create Date: 2025-12-25 13:37:13.573959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28c33500c6c7'
down_revision: Union[str, None] = '293fd6785dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('doctors_user_id_fkey'), 'doctors', type_='foreignkey')
    op.drop_column('doctors', 'user_id')
    op.add_column('users', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.add_column('doctors', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('doctors_user_id_fkey'), 'doctors', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
