"""add_clinic_verification_data

Revision ID: 293fd6785dfc
Revises: efe81d347f56
Create Date: 2025-12-25 12:58:49.266652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '293fd6785dfc'
down_revision: Union[str, None] = 'efe81d347f56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('clinic_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tenants', sa.Column('year_of_establishment', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('speciality_offer', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('clinic_registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tenants', sa.Column('issued_authority', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'issued_authority')
    op.drop_column('tenants', 'clinic_registration_number')
    op.drop_column('tenants', 'speciality_offer')
    op.drop_column('tenants', 'year_of_establishment')
    op.drop_column('tenants', 'clinic_type')
    # ### end Alembic commands ###
