"""add_doctor_verification_fields

Revision ID: f0cda9c0c460
Revises: 28c33500c6c7
Create Date: 2025-12-25 13:43:14.612377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f0cda9c0c460'
down_revision: Union[str, None] = '28c33500c6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('medical_degree', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('doctors', sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('doctors', sa.Column('medical_council', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('doctors', sa.Column('registration_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'registration_year')
    op.drop_column('doctors', 'medical_council')
    op.drop_column('doctors', 'registration_number')
    op.drop_column('doctors', 'medical_degree')
    # ### end Alembic commands ###
